"""Unit tests for the SmartZone shim guest-pass methods.

The shim maps the shared list/create/remove methods onto the SmartZone
``identity/guestpass`` REST API: passes are listed via
``identity/guestpassList``, created via ``identity/guestpass/generate`` and
deleted via ``DELETE identity/guestpass`` with an ``idList``. The mock is
stateful so the before/after re-list logic can be exercised.
"""

import json
import re

import pytest

from aioruckus.const import (
    ERROR_GUEST_PASS_BATCH_SIZE,
    ERROR_GUEST_PASS_KEY_INVALID,
    ERROR_INVALID_WLAN,
)

try:
    from .mock_aiohttp import CallbackResult
except ImportError:
    from mock_aiohttp import CallbackResult

pytestmark = pytest.mark.asyncio

SZ_WLAN = {"wlanId": "wlan-1", "name": "MyWiFi", "ssid": "MyWiFi",
           "zoneId": "zone-1", "zoneName": "MyZone"}

DEFAULT_GUESTS = [
    {
        "id": "24cfb9af-4b3f-4d0a-8a92-b2eba022687b",
        "userId": "afdfc09e-ef23-4d93-8598-8ed95fe67460",
        "key": "6ygwR3B2",
        "guestName": "guest-name-1",
        "remarks": "remark",
        "generatedOn": "2015/10/26 10:19:30",
        "expirationDate": "2015/10/27 10:19:30",
        "wlanRestrition": "[MyWiFi] of [MyZone]",
        "ssid": "MyWiFi",
        "wlan": {"id": "wlan-1", "name": "MyWiFi"},
        "zone": {"id": "zone-1", "name": "MyZone"},
        "passValidFor": {"expirationValue": 1, "expirationUnit": "DAY"},
        "maxDevices": {"maxDevicesAllowed": "LIMITED", "maxDevicesNumber": 3},
        "autoGeneratedPassword": True,
        "passEffectSince": "CREATION_TIME",
        "passUseDays": 0,
        "sessionDuration": {"requireLoginAgain": True, "sessionValue": 3, "sessionUnit": "DAY"},
        "domainId": "some-domain",
        "creatorUsername": "admin",
        "isDisabled": "NO",
    },
    {
        "id": "b28ff2cc-e0f6-4e58-b520-46b29be613ea",
        "userId": "ab96f27b-1145-4371-85c6-1c1eaa9aff6f",
        "key": "J8cjtQM9",
        "guestName": "guest-name-2",
        "remarks": "sdf",
        "generatedOn": "2015/10/26 09:54:36",
        "expirationDate": "2015/10/27 00:54:36",
        "wlanRestrition": "[MyWiFi] of [MyZone]",
        "ssid": "MyWiFi",
        "wlan": {"id": "wlan-1", "name": "MyWiFi"},
        "zone": {"id": "zone-1", "name": "MyZone"},
        "passValidFor": {"expirationValue": 2, "expirationUnit": "HOUR"},
        "maxDevices": {"maxDevicesAllowed": "UNLIMITED", "maxDevicesNumber": 3},
        "autoGeneratedPassword": True,
        "passEffectSince": "CREATION_TIME",
        "passUseDays": 0,
        "sessionDuration": {"requireLoginAgain": False, "sessionValue": 0, "sessionUnit": "MIN"},
        "domainId": "some-domain",
        "creatorUsername": "admin",
        "isDisabled": "NO",
    },
]


def _sz_guest_callback_factory(initial_guests=None, wlans=None):
    """Stateful REST callback for the SmartZone guest-pass endpoints.

    Serves ``query/wlan``, ``identity/guestpassList``,
    ``identity/guestpass/generate`` and ``DELETE identity/guestpass``,
    recording ``(url, json)`` tuples. The guest store is mutated by
    generates and deletes so the before/after re-list logic works.
    """
    store = {g["id"]: dict(g) for g in (initial_guests if initial_guests is not None else DEFAULT_GUESTS)}
    next_id = [10]
    requests = []

    def json_response(payload: dict, status: int = 200) -> CallbackResult:
        return CallbackResult(
            body=json.dumps(payload),
            status=status,
            headers={"Content-Type": "application/json"},
        )

    def callback(url, **kwargs):
        url_path = url.path
        body = kwargs.get("json") or {}
        requests.append((url_path, body))
        if url_path.endswith("/query/wlan"):
            wlans_list = wlans if wlans is not None else [SZ_WLAN]
            return json_response({"list": wlans_list, "hasMore": False, "totalCount": len(wlans_list)})
        if url_path.endswith("/identity/guestpassList"):
            return json_response({
                "totalCount": len(store), "hasMore": False,
                "firstIndex": 0, "list": list(store.values()),
            })
        if url_path.endswith("/identity/guestpass/generate"):
            for _ in range(body.get("numberOfPasses", 1)):
                pass_id = str(next_id[0])
                next_id[0] += 1
                store[pass_id] = {
                    "id": pass_id,
                    "userId": f"user-{pass_id}",
                    "key": body.get("passValue") or f"KEY{pass_id}",
                    "guestName": body.get("guestName", ""),
                    "remarks": body.get("remarks", ""),
                    "generatedOn": "2026/01/01 00:00:00",
                    "expirationDate": "2026/01/02 00:00:00",
                    "ssid": (body.get("wlan") or {}).get("name", ""),
                    "wlan": body.get("wlan"),
                    "zone": body.get("zone"),
                    "passValidFor": body.get("passValidFor"),
                    "maxDevices": body.get("maxDevices"),
                    "autoGeneratedPassword": body.get("autoGeneratedPassword", True),
                    "passEffectSince": body.get("passEffectSince", "CREATION_TIME"),
                    "passUseDays": 0,
                    "sessionDuration": body.get("sessionDuration"),
                    "domainId": "some-domain",
                    "creatorUsername": "admin",
                    "isDisabled": "NO",
                }
            return json_response({"id": str(next_id[0] - 1)}, status=201)
        if url_path.endswith("/identity/guestpass"):
            for guest_id in body.get("idList", []):
                for key, guest in list(store.items()):
                    if key == guest_id or guest.get("userId") == guest_id:
                        del store[key]
            return CallbackResult(status=204)
        return CallbackResult(body="\n")

    return callback, requests, store


def _register_sz_guest_routes(aiohttp_context, callback):
    """Register the SmartZone guest-pass routes (overriding defaults)."""
    aiohttp_context.post(
        re.compile(r"^https://192\.168\.0\.3:8443/wsg/api/public/v9_0/query/wlan"),
        callback=callback,
    )
    aiohttp_context.post(
        re.compile(r"^https://192\.168\.0\.3:8443/wsg/api/public/v9_0/identity/guestpassList"),
        callback=callback,
    )
    aiohttp_context.post(
        re.compile(r"^https://192\.168\.0\.3:8443/wsg/api/public/v9_0/identity/guestpass/generate"),
        callback=callback,
    )
    aiohttp_context.delete(
        re.compile(r"^https://192\.168\.0\.3:8443/wsg/api/public/v9_0/identity/guestpass"),
        callback=callback,
    )


@pytest.mark.asyncio
async def test_sz_get_guest_passes(create_sz_session, aiohttp_context):
    """Guest passes list via identity/guestpassList with normalized fields."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        guests = await session.api.get_guest_passes()

    assert len(guests) == 2
    first, second = guests
    assert first["key"] == "6ygwR3B2"
    assert first["id"] == "24cfb9af-4b3f-4d0a-8a92-b2eba022687b"
    assert first["name"] == "guest-name-1"
    assert first["ssid"] == "MyWiFi"
    assert first["created-by"] == "admin"
    assert first["create-time"] == "2015/10/26 10:19:30"
    assert first["expire-time"] == "2015/10/27 10:19:30"
    assert first["duration"] == "1"
    assert first["duration-unit"] == "day"
    assert first["reauth-enabled"] == "true"
    assert first["reauth-interval"] == "3"
    assert first["reauth-interval-unit"] == "day"
    assert first["shared-guestpass"] == "limited"
    assert first["share-number"] == "3"
    assert first["remarks"] == "remark"
    assert second["key"] == "J8cjtQM9"
    assert second["shared-guestpass"] == "unlimited"

    # the list query is scoped to the logged-in domain
    assert requests[0][0].endswith("/identity/guestpassList")
    assert requests[0][1]["filters"] == [{"type": "DOMAIN", "value": "some-domain"}]


@pytest.mark.asyncio
async def test_sz_do_add_guest_passes(create_sz_session, aiohttp_context):
    """A batch create resolves the WLAN/zone and returns only the new passes."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        created = await session.api.do_add_guest_passes(
            ssid="MyWiFi",
            duration=1,
            duration_unit="day",
            batch_size=2,
            remarks="aioruckus-test",
        )

    assert len(created) == 2
    assert all(g["id"] not in {gid for gid in ("24cfb9af-4b3f-4d0a-8a92-b2eba022687b", "b28ff2cc-e0f6-4e58-b520-46b29be613ea")} for g in created)
    assert all(g["key"] for g in created)
    assert all(g["ssid"] == "MyWiFi" for g in created)
    assert all(g["remarks"] == "aioruckus-test" for g in created)

    generate = next((path, body) for path, body in requests if path.endswith("/identity/guestpass/generate"))
    body = generate[1]
    assert body["numberOfPasses"] == 2
    assert body["guestName"]                       # auto-generated batch name
    assert body["wlan"] == {"id": "wlan-1", "name": "MyWiFi"}
    assert body["zone"] == {"id": "zone-1", "name": "MyZone"}
    assert body["passValidFor"] == {"expirationValue": 1, "expirationUnit": "DAY"}
    assert body["autoGeneratedPassword"] is True
    assert body["passEffectSince"] == "CREATION_TIME"
    assert body["maxDevices"] == {"maxDevicesAllowed": "LIMITED", "maxDevicesNumber": 1}
    assert body["remarks"] == "aioruckus-test"
    assert body["domainId"] == "some-domain"


@pytest.mark.asyncio
async def test_sz_do_add_guest_passes_batch_size_validation(create_sz_session, aiohttp_context):
    """Batch size outside 2..100 raises ValueError without any request."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        with pytest.raises(ValueError, match=ERROR_GUEST_PASS_BATCH_SIZE):
            await session.api.do_add_guest_passes(ssid="MyWiFi", batch_size=1)

    assert not [path for path, _ in requests if "guestpass" in path]


@pytest.mark.asyncio
async def test_sz_do_add_guest_passes_invalid_ssid(create_sz_session, aiohttp_context):
    """An unknown SSID raises ValueError without creating anything."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        with pytest.raises(ValueError, match=ERROR_INVALID_WLAN):
            await session.api.do_add_guest_passes(ssid="NoSuchWiFi", batch_size=2)

    assert not [path for path, _ in requests if "generate" in path]


@pytest.mark.asyncio
async def test_sz_do_add_guest_pass(create_sz_session, aiohttp_context):
    """A single guest pass is created with an auto-generated key."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        guest = await session.api.do_add_guest_pass(
            ssid="MyWiFi",
            name="single-guest",
            duration=1,
            duration_unit="day",
            remarks="aioruckus-test",
        )

    assert guest["key"]
    assert guest["id"]
    assert guest["name"] == "single-guest"
    assert guest["ssid"] == "MyWiFi"
    assert guest["remarks"] == "aioruckus-test"

    generate = next((path, body) for path, body in requests if path.endswith("/identity/guestpass/generate"))
    body = generate[1]
    assert body["numberOfPasses"] == 1
    assert body["guestName"] == "single-guest"
    assert body["autoGeneratedPassword"] is True
    assert body["passValue"] == ""


@pytest.mark.asyncio
async def test_sz_do_add_guest_pass_custom_key(create_sz_session, aiohttp_context):
    """A caller-supplied key is validated, uppercased and sent as passValue."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        guest = await session.api.do_add_guest_pass(
            ssid="MyWiFi",
            name="custom-key-guest",
            x_key="mykey123",
            duration=1,
            duration_unit="day",
        )

    assert guest["key"] == "MYKEY123"             # uppercased by the shim

    generate = next((path, body) for path, body in requests if path.endswith("/identity/guestpass/generate"))
    body = generate[1]
    assert body["autoGeneratedPassword"] is False
    assert body["passValue"] == "MYKEY123"


@pytest.mark.asyncio
async def test_sz_do_add_guest_pass_invalid_key(create_sz_session, aiohttp_context):
    """An invalid caller-supplied key raises ValueError before any request."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        with pytest.raises(ValueError, match=re.escape(ERROR_GUEST_PASS_KEY_INVALID)):
            await session.api.do_add_guest_pass(ssid="MyWiFi", x_key="bad key!")

    assert not [path for path, _ in requests if "generate" in path]


@pytest.mark.asyncio
async def test_sz_do_remove_guest_passes(create_sz_session, aiohttp_context):
    """Removal resolves keys to user ids and issues a single idList delete."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        await session.api.do_remove_guest_passes("6ygwR3B2", "J8cjtQM9")

    delete = next((path, body) for path, body in requests if path.endswith("/identity/guestpass"))
    assert delete[1] == {"idList": ["afdfc09e-ef23-4d93-8598-8ed95fe67460", "ab96f27b-1145-4371-85c6-1c1eaa9aff6f"]}

    # the passes are gone from the store
    guests = await session.api.get_guest_passes()
    assert not [g for g in guests if g["key"] in ("6ygwR3B2", "J8cjtQM9")]


@pytest.mark.asyncio
async def test_sz_do_remove_guest_passes_unknown_key(create_sz_session, aiohttp_context):
    """Removal of an unknown key raises ValueError without deleting anything."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        with pytest.raises(ValueError, match="not found"):
            await session.api.do_remove_guest_passes("NOPE")

    assert not [path for path, _ in requests if path.endswith("/identity/guestpass")]


@pytest.mark.asyncio
async def test_sz_do_remove_guest_passes_no_keys(create_sz_session, aiohttp_context):
    """Removal with no keys is a no-op."""
    callback, requests, _ = _sz_guest_callback_factory()
    async with create_sz_session() as session:
        _register_sz_guest_routes(aiohttp_context, callback)
        await session.api.do_remove_guest_passes()

    assert not [path for path, _ in requests if path.endswith("/identity/guestpass")]
