"""Type Hints for SmartZone JSON Payloads"""

import sys

if sys.version_info >= (3, 11):
    from typing import Literal, Required, TypedDict
else:
    from typing_extensions import Literal, Required, TypedDict

from .ajaxtyping import L2Rule


class PermissionResourceItemDict(TypedDict, total=False):
    """A per-resource permission entry inside a permission category."""
    resource: str
    access: Literal["NA", "READ", "MODIFY", "FULL_ACCESS"]
    display: str

class PermissionCategoryDict(TypedDict, total=False):
    """A permission category with the access level granted to the user."""
    resource: Required[str]
    access: Required[Literal["READ", "MODIFY", "FULL_ACCESS"]]
    display: str
    items: list[PermissionResourceItemDict]
    itemsDescription: list[str]
    ids: list[str]

class PermissionExtraDict(TypedDict, total=False):
    """Extra flags describing the admin role of the logged-in user."""
    isSuperAdmin: bool
    isSuperAdminOfDomain: bool

class PermissionCategoriesDict(TypedDict, total=False):
    """Paginated list of permission categories for the current user."""
    totalCount: int
    hasMore: bool
    firstIndex: int
    list: Required[list[PermissionCategoryDict]]
    extra: PermissionExtraDict

class SessionDict(TypedDict, total=False):
    """SmartZone session payload describing the logged-in user and cluster."""
    cpId: Required[str]
    domainId: Required[str]
    adminId: Required[str]
    apiVersion: Required[str]
    controllerVersion: Required[str]
    permissionCategories: Required[PermissionCategoriesDict]
    partnerDomain: str
    cpName: str
    cpSerialNumber: str

class BlockClientZoneDict(TypedDict, total=False):
    """A zone in which a client is blocked."""
    id: Required[str]
    zoneId: Required[str]
    description: str
    modifiedDateTime: int
    modifierUsername: str

class BlockClientDict(L2Rule, total=False):
    """A blocked client MAC with the zones it is blocked in."""
    zones: Required[list[BlockClientZoneDict]]

class GuestPassDict(TypedDict, total=False):
    """A SmartZone identity guest pass payload."""
    id: str
    userId: str
    key: str
    guestName: str
    remarks: str
    generatedOn: str
    expirationDate: str
    wlanRestrition: str
    ssid: str
    domainId: str
    creatorUsername: str
    isDisabled: str
    autoGeneratedPassword: bool
    passEffectSince: str
    passUseDays: int
    wlan: dict
    zone: dict
    passValidFor: dict
    maxDevices: dict
    sessionDuration: dict
